### ISSUE TITLE
set CI

### ISSUE THREAD

**Issue by Nikoleta-v3** [BrianAronson/birankr#19]
Setup a CI for the test suite.

There are several CIs that work well with GitHub. Recently I have been using [GitHub actions](https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow). Another commonly used CI is [Travis](https://docs.travis-ci.com/user/tutorial/#to-get-started-with-travis-ci-using-github).

**Comment by yangkcatiu** [comment]
Github actions for the python version is ready.

**Comment by BrianAronson** [comment]
Travis CI for the R version is ready.
