### ISSUE TITLE
instructions for running tests

### ISSUE THREAD

**Issue by Nikoleta-v3** [BrianAronson/birankr#20]
Include instructions on the README on how to run the tests implemented for the package.

**Comment by yangkcatiu** [comment]
@BrianAronson Please add instructions for the R part, I'll take care of the python part.

**Comment by yangkcatiu** [comment]
https://github.com/BrianAronson/birankr/commit/212e8b2dd3ff9a13892a1fd6b44b62c36ede0c51 adds the instruction for running unit tests for the python version.

**Comment by BrianAronson** [comment]
https://github.com/BrianAronson/birankr/commit/5c2d7c9e1ff5a47d60609fc6d36d2a067090c145 adds instructions for running unit tests for the R version.

**Comment by Nikoleta-v3** [comment]
Thank you both for addressing my comments.
