### ISSUE TITLE
`install_requires` requirements bounds

### ISSUE THREAD

**Issue by Nikoleta-v3** [BrianAronson/birankr#21]
It's best practice to indicate any known lower or upper bounds to the requirements listed in the `install_requires` (in the `setup.py` file) .

For example:

```
install_requires=[
    'numpy>=1.17.0'
    ...
]
```

Adding lower bounds to the requirements is encouraged.

**Comment by yangkcatiu** [comment]
https://github.com/BrianAronson/birankr/commit/80b68b95c1e23dd9695dbb534664a7fbdb653947 should address this issue.
