### ISSUE TITLE
JOSS:  state of the field & statement of need 

### ISSUE THREAD

**Issue by Nikoleta-v3** [BrianAronson/birankr#23]
> State of the field: Do the authors describe how this software compares to other commonly-used packages?

You very nicely compare your methodolody to the common one-mode projections approach. However, the paper is missing a few sentences explaining how the software compares to other packages.

This bring me to:

> A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

You clearly state the problems the software is designed to solve, but not the target audience. Following my comment above I think you should also add a sentence that you specify this.

**Comment by yangkcatiu** [comment]
https://github.com/BrianAronson/birankr/commit/76fd35dc2456753ddc5432a2b484cdd751e82460 includes new sentences addressing these issues.
