### ISSUE TITLE
JOSS: minor edit comments

### ISSUE THREAD

**Issue by Nikoleta-v3** [BrianAronson/birankr#24]
>  we present BiRank, a R and Python package that performs PageRank 

`an R` package? I am not 100% sure. 

> but in many applications, we tend to prefer CoHITS over HITS as CoHITS ranks are less influenced by the presence of outliers with extreme degrees.

Is this a personal preference or a field preference? If it's a field preference please reference.

**Comment by yangkcatiu** [comment]
Thanks for the feedback. Regarding the first comment, we implemented the same functionality both in R and Python.

The R version is available through: https://cran.r-project.org/web/packages/birankr/index.html
And the Python version available through: https://pypi.org/project/birankpy/ 

Hope this address your question.

**Comment by Nikoleta-v3** [comment]
Sorry my comment was not clear.

In the `paper.md` you have written `we present BiRank, a R package`. I believe it should say `an R package`, you are missing a `n`.

**Comment by yangkcatiu** [comment]
Sorry I misunderstood. This is a good catch. I did some googling and believe you are correct, should be `an R package`. https://github.com/BrianAronson/birankr/commit/720c08e87551d4db92c351e8ab99c4c6694dee24 should fix this.

**Comment by Nikoleta-v3** [comment]
No worries at all. I should have specified that both my comments are regarding the paper: https://github.com/BrianAronson/birankr/blob/master/paper.md

**Comment by Nikoleta-v3** [comment]
Ιn the `paper.md` you state that:

> but in many applications, we tend to prefer CoHITS over HITS as CoHITS ranks are less influenced by the presence of outliers with extreme degrees.

Is this a personal preference or a field preference? If it's a field preference please add a reference.

**Comment by BrianAronson** [comment]
Thank you for catching the missing reference. I have updated the manuscript to reference a paper that explicitly recommends CoHITS over HITS. https://github.com/BrianAronson/birankr/commit/f04d0879e0e4552b408e91c5343cf05bacee4807

**Comment by Nikoleta-v3** [comment]
Thank you both for addressing my comments.

**Comment by yangkcatiu** [comment]
Thank you for the feedback, we really appreciate it!
