### ISSUE TITLE
[JOSS] test results

### ISSUE THREAD

**Issue by gvegayon** [BrianAronson/birankr#26]
This is regarding the JOSS review https://github.com/openjournals/joss-reviews/issues/2315

I see that the R package has tests, but most of them (if not all) are focused on catching errors and equivalences instead of looking at the actual numbers. It would be nice to see that you guys are including tests in which you know what are the exact results, e.g. a real-world (or simulated) network compute the ranks "by hand" (i.e. not using your functions), and compare those results to what your functions return. That would be (a) reassuring for the users, and (b) very nice.

**Comment by yangkcatiu** [comment]
@BrianAronson I'll work on the test cases.

**Comment by yangkcatiu** [comment]
@gvegayon In https://github.com/BrianAronson/birankr/pull/27 I created several small toy networks and calculated the ranks by hand for testing the functions. Let me know what you think!

**Comment by BrianAronson** [comment]
@yangkcatiu Thanks for this. I will duplicate these in the R package.

**Comment by BrianAronson** [comment]
@gvegayon thank you for your suggestion. The following commit adds tests per your recommendation in the R version of the package. https://github.com/BrianAronson/birankr/commit/11ec4096e2a8afe0c8cd63ca8d55709d2858172f

**Comment by gvegayon** [comment]
This is great, thanks!
