### ISSUE TITLE
Colliding packages, needs update

### ISSUE THREAD

**Issue by lenkahas** [BrianAronson/birankr#30]
Hi, I was using the package for the last two weeks, it's very useful!

Unfortunately, the package dependencies are not compatible with the recent version of the networkx. For now, it only works if you install it in an already opened environment, but once the environment is closed, it collapses. This means that every time I want to use it, I need to start a new environment. 

It would be great to have the package updated, when possible.

**Comment by BrianAronson** [comment]
Thanks for your feedback.

Could you give me a little more detail, perhaps with example code and
output from the console?

**Comment by lenkahas** [comment]
Sorry, I should have done it already.

Installing package within opened environment works somehow successfully;

`Collecting birankpy
  Using cached birankpy-1.0.0-py3-none-any.whl (6.1 kB)
Requirement already satisfied: numpy>=1.16.2 in c:\users\...\gr1\lib\site-packages (from birankpy) (1.20.2)
Requirement already satisfied: scipy>=1.2.0 in c:\users\...\gr1\lib\site-packages (from birankpy) (1.6.2)
Requirement already satisfied: pandas>=0.23.4 in c:\users\....\gr1\lib\site-packages (from birankpy) (1.2.3)
Collecting networkx==2.2
  Using cached networkx-2.2-py2.py3-none-any.whl
Requirement already satisfied: decorator>=4.3.0 in c:\users\....\gr1\lib\site-packages (from networkx==2.2->birankpy) (4.4.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\....\gr1\lib\site-packages (from pandas>=0.23.4->birankpy) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\.....\gr1\lib\site-packages (from pandas>=0.23.4->birankpy) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\....\gr1\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.23.4->birankpy) (1.15.0)
Installing collected packages: networkx, birankpy
  Attempting uninstall: networkx
    Found existing installation: networkx 2.5.1
    Uninstalling networkx-2.5.1:
      Successfully uninstalled networkx-2.5.1
Successfully installed birankpy-1.0.0 networkx-2.2`

Within that opened environment is everything working fine then, until the kernel is killed.

and then if I restart the kernel and try to load the networkx again, I get;

`import networkx as nx`
`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-f17d728e971c> in <module>
----> 1 import networkx as nx

~\Anaconda3\envs\gr1\lib\site-packages\networkx\__init__.py in <module>
    112 from networkx.relabel import *
    113 
--> 114 import networkx.generators
    115 from networkx.generators import *
    116 

~\Anaconda3\envs\gr1\lib\site-packages\networkx\generators\__init__.py in <module>
     12 from networkx.generators.expanders import *
     13 from networkx.generators.geometric import *
---> 14 from networkx.generators.intersection import *
     15 from networkx.generators.joint_degree_seq import *
     16 from networkx.generators.lattice import *

~\Anaconda3\envs\gr1\lib\site-packages\networkx\generators\intersection.py in <module>
     11 import random
     12 import networkx as nx
---> 13 from networkx.algorithms import bipartite
     14 from networkx.utils import py_random_state
     15 

~\Anaconda3\envs\gr1\lib\site-packages\networkx\algorithms\__init__.py in <module>
     14 from networkx.algorithms.cycles import *
     15 from networkx.algorithms.cuts import *
---> 16 from networkx.algorithms.dag import *
     17 from networkx.algorithms.distance_measures import *
     18 from networkx.algorithms.distance_regular import *

~\Anaconda3\envs\gr1\lib\site-packages\networkx\algorithms\dag.py in <module>
     21 
     22 from collections import defaultdict, deque
---> 23 from fractions import gcd
     24 from functools import partial
     25 from itertools import chain

**ImportError: cannot import name 'gcd' from 'fractions' (C:\Users\....\gr1\lib\fractions.py)`**

I have been searching online what is the problem and figured out there might be some collision within the networkx and birankpy.

I would be very grateful for any advice.

**Comment by jboynyc** [comment]
Same issue here. I think the root cause is explained [here](https://stackoverflow.com/questions/66174862/import-error-cant-import-name-gcd-from-fractions). The short version is that `birankpy` pins `networkx` 2.2, but that version isn't compatible with Python 3.9+ because it still looks for `gcd` in the `fractions` module, but it has been moved to the `math` module. Updating to `networkx` version 2.5 or above should do the trick.

**Comment by yangkcatiu** [comment]
Thank you!
