### ISSUE TITLE
Write the paper.md

### ISSUE THREAD

**Issue by yangkcatiu** [BrianAronson/birankr#4]
- [x] Draft the paper in latex
- [x] Convert it to paper.md

**Comment by yangkcatiu** [comment]
Requirements of the paper:
- [ ] A list of the authors of the software and their affiliations, using the correct format (see the example below).
- [ ] A summary describing the high-level functionality and purpose of the software for a diverse, non-specialist audience.
- [ ] A clear Statement of Need that illustrates the research purpose of the software.
- [ ] A list of key references, including to other software addressing related needs.
- [ ] Mention (if applicable) of any past or ongoing research projects using the software and recent scholarly publications enabled by it.
- [ ] Acknowledgement of any financial support.

**Comment by BrianAronson** [comment]
I'm not quite sure how to convert the latex table formats to R.

**Comment by yangkcatiu** [comment]
We need to convert it to Markdown (https://guides.github.com/features/mastering-markdown/), don't worry, I'll take care of it.

**Comment by BrianAronson** [comment]
Right, that's what I meant - markdown. Sorry, I think of markdown as synonymous with R since markdown is sort of the R's equivalent to what Jupyter notebooks is for Python.

**Comment by yy** [comment]
Well, Jupyter notebook uses Markdown too, just like R markdown.
