### ISSUE TITLE
Prepare an example of the package

### ISSUE THREAD

**Issue by yangkcatiu** [BrianAronson/birankr#9]
We can provide an example to demonstrate the package. I think the Marvel social network is a pretty good choice. I created a Python version at https://github.com/BrianAronson/birankr/blob/py/examples/Marvel_social_network.ipynb , would be nice if we can also have a R version, and replace the patient provider network example with it in the README.md.

**Comment by BrianAronson** [comment]
Agreed. Will do asap

**Comment by yangkcatiu** [comment]
No rush. I have plenty to do for the python version.

**Comment by BrianAronson** [comment]
R version made in https://github.com/BrianAronson/birankr/blob/master/examples/Marvel_social_network.md

**Comment by yangkcatiu** [comment]
Nice!
